# app/application/ports.py
from typing import Protocol, Iterable, Optional
from app.domain.models import Meeting

class IO(Protocol):
    """UI-agnostic input/output."""
    def ask(self, prompt: str) -> str: ...
    def info(self, msg: str) -> None: ...
    def warn(self, msg: str) -> None: ...
    def confirm(self, prompt: str) -> bool: ...
    def list_events(self, events: Iterable, tz: str) -> None: ...
    def review_summary(self, summary: dict) -> None: ...

class Calendar(Protocol):
    """Minimal calendar port (in-memory today; Google/Outlook later)."""
    def first_conflict(self, meeting: Meeting) -> Optional[str]: ...
    def create_event(self, meeting: Meeting) -> None: ...
    def list_all(self) -> Iterable: ...
